# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: url_search.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10url_search.proto\x1a\x1egoogle/protobuf/duration.proto\".\n\tThreatUrl\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x14\n\x0cthreat_types\x18\x02 \x03(\x05\"d\n\x12SearchUrlsResponse\x12\x1b\n\x07threats\x18\x01 \x03(\x0b\x32\n.ThreatUrl\x12\x31\n\x0e\x63\x61\x63he_duration\x18\x02 \x01(\x0b\x32\x19.google.protobuf.Durationb\x06proto3')



_THREATURL = DESCRIPTOR.message_types_by_name['ThreatUrl']
_SEARCHURLSRESPONSE = DESCRIPTOR.message_types_by_name['SearchUrlsResponse']
ThreatUrl = _reflection.GeneratedProtocolMessageType('ThreatUrl', (_message.Message,), {
  'DESCRIPTOR' : _THREATURL,
  '__module__' : 'url_search_pb2'
  # @@protoc_insertion_point(class_scope:ThreatUrl)
  })
_sym_db.RegisterMessage(ThreatUrl)

SearchUrlsResponse = _reflection.GeneratedProtocolMessageType('SearchUrlsResponse', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHURLSRESPONSE,
  '__module__' : 'url_search_pb2'
  # @@protoc_insertion_point(class_scope:SearchUrlsResponse)
  })
_sym_db.RegisterMessage(SearchUrlsResponse)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _THREATURL._serialized_start=52
  _THREATURL._serialized_end=98
  _SEARCHURLSRESPONSE._serialized_start=100
  _SEARCHURLSRESPONSE._serialized_end=200
# @@protoc_insertion_point(module_scope)
